
#define	WM_CLOSE_DIALOG		WM_USER+1
#define	WM_ICON				WM_USER+2
#define WM_SEARCH			WM_USER+3
#define WM_TASKFINISHED		WM_USER+4
#define WM_SEARCH_FINISHED	WM_USER+5
#define IDC_MAINLIST		WM_USER+6	//control
#define WM_TREEITEM_SELECTED	WM_USER+7
#define WM_THREAD_FINISHED	WM_USER+8
#define WM_NETFRIEND_ADD	WM_USER+9

#define WM_P2P_APPENDUSERINFO	WM_USER+10
#define WM_P2P_DELETEUSERINFO	WM_USER+11
#define WM_P2P_COMM_DLG_COMM	WM_USER+12
#define WM_P2P_APPEND_SHARE_LIST WM_USER+13
#define WM_P2P_CONNECT_FRIEND	WM_USER+14
#define WM_FILEDOWNLOAD		WM_USER+15
#define WM_P2P_FILEDOWNLOAD_FINISHED	WM_USER+16


#define WM_OPEN_FILE	WM_USER+17
#define WM_PAGENUM_CHANGE	WM_USER+18
#define WM_CURPAGE_CHANGE	WM_USER+19
#define WM_UP_PAGE			WM_USER+20
#define WM_DOWN_PAGE		WM_USER+21
#define WM_ZOOM				WM_USER+22
#define WM_OPEN_URL			WM_USER+23
#define WM_REQUEST_RESUOURCE_FROM_SERVER	WM_USER+24
#define WM_BEGIN_DOWNLOAD	WM_USER+25
#define WM_SERVER_ERROR		WM_USER+26
#define WM_SENDFILE			WM_USER+27
#define WM_COMM_CONNECT		WM_USER+28

#define WM_ADD_ORDER_ITEM	WM_USER+29

#define IDC_TIPDLG_BUTTON_OK WM_USER+30
#define IDC_TIPDLG_CHECK	WM_USER+31

#define WM_P2P_FILEDOWNLOAD_ERROR	WM_USER+32

#define IDC_TREE_WOLMENU	WM_USER+33
#define WM_BUTTON_MENU	WM_USER+34

#define WM_SOCKET_FINISHED	WM_USER+35

#define WM_SYN_TO_SD	WM_USER+36

#define WM_APPENDGROUPINFO	WM_USER+37
#define WM_DELETEGROUPINFO	WM_USER+38

#define WM_SHOW_GROUPRESOURCE	WM_USER+39
#define WM_SHOW_USERSOURCE	WM_USER+40

#define WM_CLIENTTHREAD_FINISHED WM_USER+41

#define WM_CREATE_TALK_DLG	WM_USER+42

#define WM_CREATE_FAVORFOLDER	WM_USER+43

#define WM_OPENWINDOW WM_USER + 44
#define  WM_CLOSEWINDOW WM_USER + 45

#define WM_SEARCHCACHE			WM_USER+46
#define WM_FINISHED_DIALOG		WM_USER+47
#define WM_OPEN_TAG_URL			WM_USER+48
#define WM_SEARCHCOUNT_UPDATE   WM_USER+49
#define WM_UPDATE_GUIDETREECOUNT WM_USER+50
#define WM_OPEN_URL_NOT_SHOW WM_USER+51
#define	WM_ADD_TO_MYHALL    WM_USER+52
#define WM_RECORD_BEHAVIOR	WM_USER+53
#define WM_SEND_CHAT_INFO1  WM_USER+54
#define WM_SEND_CHAT_INFO2  WM_USER+55 //added by zhanganzhan on 20090326
#define WM_USER_TREE_CLICKED WM_USER+56
#define WM_USER_ADD_RICKER    WM_USER+57
#define WM_USER_REFRESH       WM_USER+58
#define WM_MAINFRAME_REFRESH_USER WM_USER+59
#define WM_SEND_CHAT_INFO WM_USER+60
#define WM_NEW_DOWNLOAD  WM_USER+61 //added by fangji on 20190401
#define WM_UPDATE_DOWNLOAD  WM_USER+62
#define IDC_LST_MENU WM_USER + 1000
//http://61.181.14.187/share/main.asp?modelflag=5



#define PROCESS_WM				WM_USER+400

#define PROCESS_WM_NOTIFY_NAME	PROCESS_WM+0			
#define PROCESS_WM_MSG_SEND		PROCESS_WM+1
#define PROCESS_WM_MSG_RECV		PROCESS_WM+2