//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Readings.rc
//
#define IDC_BUTTON_NEWTYPE              3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_READINTYPE                  129
#define IDD_MAINBAR                     130
#define IDD_DIALOG_REG                  131
#define IDB_BITMAP_BGREGST              132
#define IDB_BITMAP_LOGIN                133
#define IDB_BITMAP_GUEST                134
#define IDB_BITMAP_REG                  135
#define IDB_BITMAP_GETPWD               136
#define IDC_CURSOR                      137
#define IDD_DIALOG_HTTPDOWN             139
#define IDB_MAINBAR_REFRESH             141
#define IDB_MAINBAR_REFRESH_CHK         142
#define IDB_MAINBAR_REFRESH_SEL         143
#define IDB_MAINBAR_REFRESH_DIS         144
#define IDB_MAINBAR_SYN                 145
#define IDB_MAINBAR_SYN_CHK             146
#define IDB_MAINBAR_SYN_DIS             147
#define IDB_MAINBAR_SYN_SEL             148
#define IDB_MAINBAR_ORDER               158
#define IDB_MAINBAR_ORDER_CHK           159
#define IDB_MAINBAR_ORDER_SEL           160
#define IDB_MAINBAR_ORDER_DIS           161
#define IDB_MAINBAR_RESEARCH_STR        162
#define IDB_MAINBAR_SEARCH_CHK          163
#define IDB_MAINBAR_SEARCH_SEL          164
#define IDB_MAINBAR_SEARCH_DIS          165
#define IDB_MAINBAR_SEARCH              166
#define IDB_MAINBAR_HISTORY             168
#define IDB_MAINBAR_HISTORY_CHK         169
#define IDB_MAINBAR_HISTORY_DIS         170
#define IDB_MAINBAR_HISTORY_SEL         171
#define IDB_MAINBAR_USERADV             172
#define IDB_MAINBAR_USERADV_DIS         173
#define IDB_MAINBAR_USERADV_SEL         174
#define IDB_MAINBAR_USERADV_CHK         175
#define IDB_MAINBAR_HELP_DIS            176
#define IDB_MAINBAR_HELP_CHK            177
#define IDB_MAINBAR_HELP                178
#define IDB_MAINBAR_HELP_SEL            179
#define IDB_IMGLIST_TREE                180
#define IDD_DIALOG_SHOW                 181
#define IDB_SEARCHLIST_ICON             183
#define IDB_SEARCHLIST_ICON_NAIL        184
#define IDB_SEARCHLIST_ICON_GOOGLE      185
#define IDB_SEARCHLIST_ICON_BAIDU       186
#define IDB_SEARCHLIST_ICON_LOCAL       187
#define IDB_SEARCHLIST_ICON_VERYCD      188
#define IDB_SEARCHLIST_ICON_ISTATION    189
#define IDB_SEARCHLIST_ICON_READMAN     190
#define IDB_SEARCHLIST_ICON_PDFPAPER    191
#define IDB_SEARCHLIST_ICON_ZCOM        193
#define IDB_SEARCHLIST_ICON_MOBILE      194
#define IDB_SEARCHLIST_ICON_EBOOK       195
#define IDB_SEARCHLIST_ICON_COMPUTER    196
#define IDB_SEARCHLIST_ICON_SOURCE      197
#define IDB_BITMAP_BUTTON_ORDER         198
#define IDB_BITMAP_BUTTON_ADDTOORDER    199
#define IDB_BITMAP_BUTTON_READ          200
#define IDB_BITMAP_BUTTON_SYN_CHK       201
#define IDB_BITMAP_BUTTON_SYN_EMP       202
#define IDB_BITMAP_BUTTON_BROWSE        203
#define IDB_BITMAP_BUTTON_DOWNLOAD      204
#define IDB_BITMAP_BUTTON_MAKEWOLF      205
#define IDR_READINGS                    206
#define IDB_FILEICON_3DSMALLBOOK        207
#define IDB_BITMAP_BUTTON_STOPSEARCH    208
#define IDB_BITMAP_BUTTON_STOPSEARCH_CHK 209
#define IDB_BITMAP_BUTTON_STOPSEARCH_DIS 210
#define IDB_BITMAP_BUTTON_STOPSEARCH_SEL 211
#define IDD_DIALOG_COMMDLG              212
#define IDB_IMGLIST_DOWNLOAD            213
#define IDB_SEARCHLIST_ICON_SINABOOK    214
#define IDB_BITMAP_BUTTON_TRYMAKEWOLF   215
#define IDB_UP                          216
#define IDB_DOWN                        217
#define IDB_LEFT                        218
#define IDB_RIGHT                       219
#define IDR_TRAYMENU                    220
#define IDD_DIALOG_READ                 221
#define IDB_BITMAP_LOGO                 222
#define IDD_CONTROLBAR                  223
#define IDB_CTLBAR_LEFT                 224
#define IDB_CTLBAR_RIGHT                225
#define IDB_CTLBAR_MENU                 226
#define IDB_CTLBAR_ZOOM                 227
#define IDB_SEARCHLIST_ICON_SHARE       228
#define IDB_BITMAP_BUTTON_ORDER_CHK     229
#define IDB_BITMAP_BUTTON_ORDER_EMP     230
#define IDD_DIALOG_TIP                  231
#define IDB_TIPDLG_ALERT                232
#define IDB_TIPDLG_BUTTON               233
#define IDB_TIPDLG_MESSAGE              234
#define IDB_TIPDLG_QUESTION             235
#define IDB_TIPDLG_TIP                  236
#define IDR_MENU_DL                     237
#define IDD_DIALOG_SYN                  238
#define IDD_DIALOG_SYN_LIST             239
#define IDB_IMGLIST_FILE                240
#define IDD_SELPATH_DIALOG              241
#define IDD_DIALOG_INPUT                242
#define IDR_MENU_LIST                   243
#define IDR_MENU_TREE                   245
#define IDD_DIALOG_CONFIG               246
#define IDB_BMPLIST_CONFIG              247
#define IDD_CONFIGPAGE_SHARE            248
#define IDD_CONFIGPAGE_NORMAL           249
#define IDD_CONFIGPAGE_FAVOR            250
#define IDD_CONFIGPAGE_SERVER           251
#define IDD_CONFIGPAGE_PUSH             252
#define IDI_ICON_EMPTY                  254
#define IDI_ICON_MSG                    255
#define IDR_WAVE_DANG                   256
#define IDR_MENU_RIGHTTREE              258
#define IDD_DIALOG_NEWRG                259
#define IDD_DIALOG_TALK                 260
#define IDD_DIALOG_WATERMARKLINK        263
#define IDB_MAINBAR_OPEN                265
#define IDB_MAINBAR_OPEN_CHK            266
#define IDB_MAINBAR_OPEN_SEL            267
#define IDB_MAINBAR_OPEN_DIS            268
#define IDB_MAINBAR_CLOSE               269
#define IDB_MAINBAR_CLOSE_CHK           270
#define IDB_MAINBAR_CLOSE_DIS           271
#define IDB_MAINBAR_CLOSE_SEL           272
#define IDB_BITMAP_BUTTON_DOWNLOADH     273
#define IDB_BITMAP_BUTTON_BROWSEH       274
#define IDB_BITMAP1                     275
#define IDB_BITMAP_BUTTON_GROUP         276
#define IDD_DIALOG_CLASSIFY             277
#define IDR_MENU_RE_GROUP               278
#define IDD_DIALOG_CREATE_REGROUP       280
#define IDD_DIALOG_RGROUPKEYWORD        281
#define IDD_DIALOG_BACKUP               282
#define IDB_BITMAP_BUTTON_COMMENT       284
#define IDD_DIALOG_COMMENTS             285
#define IDB_BITMAP_BLANKSTAR            287
#define IDB_BITMAP_STAR                 288
#define IDB_SEARCHLIST_ICON_HUNTMINE    295
#define IDB_SEARCHLIST_ICON_OPENCOURSE  296
#define IDB_BITMAP2                     299
#define IDB_BITMAP_DWZL                 299
#define IDB_BITMAP3                     300
#define IDB_BITMAP_KJFL                 300
#define IDB_BITMAP4                     301
#define IDB_BITMAP_WJSX                 301
#define IDB_BITMAP5                     302
#define IDB_BITMAP_YJXX                 302
#define IDB_BITMAP6                     303
#define IDB_BITMAP_DJHD                 303
#define IDB_BITMAP_BUTTON_COMMENT_FALSE 304
#define IDB_SEARCHLIST_ICON_DU8         305
#define IDD_DIALOG_COMMLOG              306
#define IDC_CURSOR1                     307
#define IDC_CURSOR2                     308
#define IDD_DIALOG_USERINFO             310
#define IDB_BITMAP7                     311
#define IDB_SEARCHLIST_ICON_BAIDUE      315
#define IDB_SEARCHLIST_ICON_DUXIU       317
#define IDB_BITMAP_BUTTON_EMAIL_R       319
#define IDD_DIALOG_SMS                  320
#define IDD_DIALOGADDUNIVERSITY         321
#define IDD_DIALOG_ADDSTUDYBUILDING     322
#define IDD_RECVMAILDIALOG              324
#define IDD_REQUESTMAILDIALOG           325
#define IDD_DIALOG_MAIL                 326
#define IDD_DIALOG_ZST                  327
#define IDB_BITMAP_ZST                  328
#define IDD_DIALOG1                     329
#define IDD_DIALOG_TABNEW               329
#define IDD_DIALOG2                     330
#define IDD_YESNODIALOG                 330
#define IDR_MENU_DOWNLOAD               331
#define IDD_DIALOG_HOTKEY               332
#define IDR_MENU_NETBOOK                333
#define IDD_DIALOG_ADDNETBOOK           334
#define IDD_REFUSETMAILDIALOG           336
#define IDD_MailHistory                 337
#define IDR_MENU_MYRESOURCE             337
#define IDD_AGREEMAILDIALOG             338
#define IDD_CHARGETMAILDIALOG           339
#define IDC_HANDCUR                     342
#define IDC_DRAGGING                    343
#define IDC_NODRAGGING                  344
#define IDD_drawers                     345
#define IDB_SEARCHLIST_ICON_DANGDANG    350
#define IDB_BITMAP_BUTTON_BUY           352
#define IDB_SEARCHLIST_ICON_FANSHU      355
#define IDD_DIALOG_AUTO_LOGIN           356
#define IDB_SEARCHLIST_ICON_BDWENKU     361
#define IDB_SEARCHLIST_ICON_SINAIASK    362
#define IDB_BITMAP_BUTTON_ZHANKAI       363
#define IDB_BITMAP_BUTTON_SHOUQI        364
#define IDB_SEARCHLIST_ICON_MAKEBOOK    365
#define IDD_DIALOG3                     366
#define IDD_DIALOG_Error_Exit           367
#define IDC_BUTTON_GUEST                1000
#define IDC_BUTTON_REG                  1001
#define IDC_BUTTON_GETPWD               1002
#define IDC_EDIT_PASSWORD               1004
#define IDC_CHECK_OFFLINE               1005
#define IDC_CHECK_SAVE                  1006
#define IDC_CHECK_AUTOLOG               1007
#define IDC_COMBO_SERVER                1008
#define IDC_COMBO_SEL_REMOVEDISK        1009
#define IDC_COMBO_USERNAME              1010
#define IDC_STATIC_TIP                  1012
#define IDC_BUTTON_REFRESH              1013
#define IDC_BUTTON_ORDERLIST            1014
#define IDC_BUTTON_SYN                  1015
#define IDC_BUTTON_SEARCH_STR           1016
#define IDC_BUTTON_HISTORY              1017
#define IDC_BUTTON_USERADV              1018
#define IDC_BUTTON_HELP                 1019
#define IDC_BUTTON_SEARCH               1020
#define IDC_EDIT1                       1021
#define IDC_EDIT_SEARCH_KEY             1021
#define IDC_EDIT_USERNAME               1021
#define IDC_EXPLORER                    1022
#define IDC_EDIT_NICKNAME               1022
#define IDC_EDIT_KEY2                   1022
#define IDC_KEY2                        1022
#define IDC_EDIT_EDUCOLLEGE             1023
#define IDC_EDIT_KEY3                   1023
#define IDC_KEY3                        1023
#define IDC_EDIT_FIELD                  1024
#define IDC_EDIT_KEY4                   1024
#define IDC_EDIT_GJC2                   1024
#define IDC_EDIT_LOCATION               1025
#define IDC_EDIT_KEY5                   1025
#define IDC_EDIT_GJC3                   1025
#define IDC_EDIT_CAREER                 1026
#define IDC_EDIT5                       1026
#define IDC_EDIT_REALNAME               1027
#define IDC_EDIT9                       1027
#define IDC_EDIT_SEX                    1028
#define IDC_EDIT_KEY7                   1028
#define IDC_EDIT_PCC2                   1028
#define IDC_EDIT_AGE                    1029
#define IDC_EDIT_KEY8                   1029
#define IDC_EDIT_PCC3                   1029
#define IDC_EDIT_CONSTELLATION          1030
#define IDC_EDIT_KEY9                   1030
#define IDC_EDIT_XXC2                   1030
#define IDC_EDIT_BIRTH_MONTH            1031
#define IDC_EDIT_KEY10                  1031
#define IDC_EDIT_XXC3                   1031
#define IDC_EDIT_BIRTH_DAY              1032
#define IDC_EDIT_KEY13                  1032
#define IDC_EDIT_ZSD2                   1032
#define IDC_EDIT_EMAIL                  1033
#define IDC_EDIT_KEY14                  1033
#define IDC_EDIT_ZSD3                   1033
#define IDC_LIST_FRIEND_RESOURCE        1034
#define IDC_EDIT_KEY17                  1034
#define IDC_EDIT_ZYC2                   1034
#define IDC_EDIT_RECIEVE                1035
#define IDC_EDIT_KEY18                  1035
#define IDC_EDIT_ZYC3                   1035
#define IDC_EDIT_SEND                   1036
#define IDC_EDIT_KEY19                  1036
#define IDC_EDIT14                      1036
#define IDC_BUTTON_CLOSE                1037
#define IDC_EDIT_KEY20                  1037
#define IDC_EDIT17                      1037
#define IDC_BUTTON_SEND                 1038
#define IDC_EDIT_KEY22                  1038
#define IDC_TAB                         1039
#define IDC_EDIT_KEY23                  1039
#define IDC_BUTTON1                     1040
#define IDC_BUTTON_LEFT                 1040
#define IDC_BUTTON_FC                   1040
#define IDC_BUTTON_SELALL               1040
#define IDC_BUTTON_ADDSHARE             1040
#define IDC_BUTTON_FAVORFOLDER_BROWSE   1040
#define IDC_BUTTON_AUTO_DETECT          1040
#define IDC_BUTTON_OPEN_CLOSE           1040
#define IDC_BUTTON_DEL                  1040
#define IDC_BUTTON_MSGRECORD            1040
#define IDC_BUTTON_SUBMIT               1040
#define IDC_HISTORY_UP                  1040
#define IDC_SMS_EXPLORER                1040
#define IDC_REFUSEBUTTON                1040
#define IDC_HistoryBUTTON               1040
#define IDC_BUTTON_ADDNETBOOK           1040
#define IDC_BUTTON2                     1041
#define IDC_BUTTON_RIGHT                1041
#define IDC_BUTTON_CANCELALL            1041
#define IDC_BUTTON_DELSHARE             1041
#define IDC_BUTTON_ADD_COLLECTFOLDER    1041
#define IDC_HISTORY_DOWN                1041
#define IDC_BUTTON_MAIL                 1041
#define IDC_AGREEBUTTON                 1041
#define IDC_BUTTON_CANCLEADD            1041
#define IDC_Reflush                     1041
#define IDC_BUTTON3                     1042
#define IDC_BUTTON_ZOOM                 1042
#define IDC_BUTTON_SELHIGHLIGHT         1042
#define IDC_BUTTON_DEL_COLLECTFOLDER    1042
#define IDC_BUTTON4                     1043
#define IDC_BUTTON_MENU                 1043
#define IDC_PROGRESS_SYN                1044
#define IDC_BUTTON5                     1044
#define IDC_SYNLIST                     1045
#define IDC_BUTTON6                     1045
#define IDC_TREE_DOWNLOAD               1046
#define IDC_BUTTON7                     1046
#define IDC_EDIT_NAME                   1047
#define IDC_BUTTON8                     1047
#define IDC_USER_TREE                   1048
#define IDC_BUTTON9                     1048
#define IDC_LIST_USER                   1049
#define IDC_BUTTON10                    1049
#define IDC_LIST_GROUP                  1050
#define IDC_LIST_SEL                    1050
#define IDC_BUTTON11                    1050
#define IDC_BUTTON12                    1051
#define IDC_CHECK_SHAREFOLDER           1052
#define IDC_BUTTON13                    1052
#define IDC_CHECK_SHAREFORMAT           1053
#define IDC_BUTTON14                    1053
#define IDC_LIST_SHAREFOLDER            1054
#define IDC_EDIT_KEY24                  1054
#define IDC_BUTTON25                    1054
#define IDC_TREE_SHAREFORMAT            1055
#define IDC_EDIT_KEY25                  1055
#define IDC_BUTTON26                    1055
#define IDC_CHECK_NEWVERSION            1056
#define IDC_BUTTON15                    1056
#define IDC_CHECK_SHOWMIN               1057
#define IDC_BUTTON16                    1057
#define IDC_CHECK_AUTORUN               1058
#define IDC_BUTTON17                    1058
#define IDC_CHECK_AUTOLOGIN             1059
#define IDC_BUTTON18                    1059
#define IDC_CHECK_CONFIRM_QUIT          1060
#define IDC_BUTTON19                    1060
#define IDC_SPIN_PAP                    1061
#define IDC_BUTTON20                    1061
#define IDC_EDIT_INTERVAL               1062
#define IDC_BUTTON21                    1062
#define IDC_RADIO_NEVER                 1063
#define IDC_BUTTON22                    1063
#define IDC_RADIO_PDF_AUTO              1064
#define IDC_BUTTON23                    1064
#define IDC_RADIO_ALL_AUTO              1065
#define IDC_BUTTON24                    1065
#define IDC_EDIT_PAPDAY                 1066
#define IDC_EDIT_KEY27                  1066
#define IDC_BUTTON33                    1066
#define IDC_EDIT_ALLDAY                 1067
#define IDC_EDIT_KEY28                  1067
#define IDC_BUTTON34                    1067
#define IDC_SPIN_ALL                    1068
#define IDC_EDIT_KEY29                  1068
#define IDC_RADIO_ALLDISK               1069
#define IDC_EDIT_KEY30                  1069
#define IDC_RADIO_SPECDISK              1070
#define IDC_EDIT_KEY32                  1070
#define IDC_LIST_COLLECT                1071
#define IDC_EDIT_KEY33                  1071
#define IDC_STATIC_TIPS                 1072
#define IDC_EDIT_KEY34                  1072
#define IDC_STATIC_TIPS2                1073
#define IDC_EDIT_KEY35                  1073
#define IDC_SPIN                        1074
#define IDC_BUTTON35                    1074
#define IDC_BUTTON27                    1074
#define IDC_EDIT_FAVORFOLDER            1075
#define IDC_BUTTON36                    1075
#define IDC_BUTTON28                    1075
#define IDC_STATIC_TIPS1                1076
#define IDC_BUTTON37                    1076
#define IDC_BUTTON29                    1076
#define IDC_STATIC_TIPS3                1077
#define IDC_BUTTON38                    1077
#define IDC_BUTTON30                    1077
#define IDC_STATIC_TIPS4                1078
#define IDC_BUTTON39                    1078
#define IDC_BUTTON31                    1078
#define IDC_IPADDRESS                   1079
#define IDC_BUTTON40                    1079
#define IDC_BUTTON32                    1079
#define IDC_EDIT_CTR_PORT               1080
#define IDC_BUTTON41                    1080
#define IDC_EDIT_TRAN_PORT              1081
#define IDC_CHECK_READMAN               1081
#define IDC_BUTTON42                    1081
#define IDC_CHECK_PUSH                  1082
#define IDC_BUTTON43                    1082
#define IDC_EDIT_SEV_PORT               1083
#define IDC_BUTTON44                    1083
#define IDC_RICHEDIT_RECV               1084
#define IDC_BUTTON45                    1084
#define IDC_EDIT_RGTITLE                1085
#define IDC_BUTTON46                    1085
#define IDC_RICHEDIT1                   1086
#define IDC_BUTTON47                    1086
#define IDC_RICHEDIT2                   1087
#define IDC_BUTTON48                    1087
#define IDC_BUTTON49                    1088
#define IDC_BUTTON50                    1089
#define IDC_TREE_GROUP                  1090
#define IDC_BUTTON51                    1090
#define IDC_TYPELIST                    1091
#define IDC_BUTTON52                    1091
#define IDC_BUTTON53                    1092
#define IDC_BUTTON54                    1093
#define static1                         1094
#define IDC_BUTTON55                    1094
#define IDC_EDIT_DES                    1095
#define IDC_BUTTON56                    1095
#define IDC_EDIT_KEY1                   1096
#define IDC_KEY1                        1097
#define IDC_EDIT_KEY6                   1097
#define IDC_EDIT_PCC1                   1097
#define IDC_EDIT_OKEYWORDS              1098
#define IDC_PROGRESS_BACKUP             1099
#define IDC_BUTTON57                    1099
#define IDC_STATIC_BACKUP               1100
#define IDC_EDIT_KEY16                  1100
#define IDC_EDIT_KEY11                  1100
#define IDC_EDIT_GJC1                   1100
#define IDC_STATIC_TIME                 1101
#define IDC_EDIT_KEY21                  1101
#define IDC_EDIT_KEY12                  1101
#define IDC_EDIT_ZSD1                   1101
#define IDC_EDIT_MYCOMMENTS             1102
#define IDC_EDIT_KEY26                  1102
#define IDC_EDIT_KEY15                  1102
#define IDC_EDIT_XXC1                   1102
#define IDC_EDIT_COMMENTS               1103
#define IDC_BUTTON58                    1103
#define IDC_EDIT_KEY36                  1103
#define IDC_EDIT_ZYC1                   1103
#define IDC_EDIT_RECORD                 1104
#define IDC_BUTTON59                    1105
#define IDC_EDIT2                       1106
#define IDC_EDIT3                       1107
#define IDC_EDIT6                       1108
#define IDC_EDIT7                       1109
#define IDC_EDIT10                      1110
#define IDC_EDIT11                      1111
#define IDC_EDIT13                      1112
#define IDC_BUTTON65                    1113
#define IDC_EDIT15                      1113
#define IDC_BUTTON66                    1114
#define IDC_EDIT18                      1114
#define IDC_BUTTON67                    1115
#define IDC_EDIT19                      1115
#define IDC_BUTTON68                    1116
#define IDC_BUTTON69                    1117
#define IDC_BUTTON_ZTC_UP               1117
#define IDC_BUTTON70                    1118
#define IDC_BUTTON_ZTC_DOWN             1118
#define IDC_BUTTON60                    1119
#define IDC_BUTTON91                    1119
#define IDC_BUTTON_PCC_UP               1119
#define IDC_BUTTON61                    1120
#define IDC_BUTTON92                    1120
#define IDC_BUTTON_PCC_DOWN             1120
#define IDC_BUTTON62                    1121
#define IDC_BUTTON63                    1122
#define IDC_BUTTON64                    1123
#define IDC_BUTTON71                    1124
#define IDC_BUTTON72                    1125
#define IDC_EDIT_KEY31                  1126
#define IDC_BUTTON73                    1127
#define IDC_BUTTON74                    1128
#define IDC_BUTTON75                    1129
#define IDC_BUTTON76                    1130
#define IDC_BUTTON77                    1131
#define IDC_BUTTON78                    1132
#define IDC_BUTTON79                    1133
#define IDC_BUTTON80                    1134
#define IDC_BUTTON81                    1135
#define IDC_BUTTON82                    1136
#define IDC_BUTTON83                    1137
#define IDC_BUTTON84                    1138
#define IDC_BUTTON85                    1139
#define IDC_BUTTON86                    1140
#define IDC_COMBO1                      1141
#define IDC_BUTTON87                    1142
#define IDC_BUTTON_GJC_UP               1142
#define IDC_BUTTON88                    1143
#define IDC_BUTTON_GJC_DOWN             1143
#define IDC_BUTTON89                    1144
#define IDC_BUTTON_ZSD_UP               1144
#define IDC_BUTTON90                    1145
#define IDC_BUTTON_ZSD_DOWN             1145
#define IDC_BUTTON93                    1146
#define IDC_BUTTON_XXC_UP               1146
#define IDC_BUTTON94                    1147
#define IDC_BUTTON_XXC_DOWN             1147
#define IDC_BUTTON95                    1148
#define IDC_BUTTON_ZYC_UP               1148
#define IDC_BUTTON96                    1149
#define IDC_BUTTON_ZYC_DOWN             1149
#define IDC_BUTTON97                    1150
#define IDC_BUTTON98                    1151
#define IDC_ZTC                         1152
#define IDC_STATIC_ZTC1                 1153
#define IDC_STATIC_ZTC2                 1154
#define IDC_STATIC_ZTC3                 1155
#define IDC_TREE_OPER                   1156
#define IDC_LIST_LOG                    1157
#define IDC_LIST_PUBINFO                1158
#define IDC_EDIT_TREENAME               1159
#define IDC_GJC                         1160
#define IDC_ZSD                         1161
#define IDC_PCC                         1162
#define IDC_XXC                         1163
#define IDC_EDIT4                       1164
#define IDC_EDIT8                       1165
#define IDC_EDIT12                      1166
#define IDC_EDIT16                      1167
#define IDC_EDIT20                      1168
#define IDC_ZYC                         1169
#define IDC_STATIC_GJC1                 1170
#define IDC_STATIC_GJC2                 1171
#define IDC_STATIC_GJC3                 1172
#define IDC_STATIC_ZSD1                 1173
#define IDC_STATIC_ZSD2                 1174
#define IDC_STATIC_ZSD3                 1175
#define IDC_EDIT_SCHOOL                 1176
#define IDC_COMBO_SCHOOL                1178
#define IDC_STATIC_NAME                 1180
#define IDC_STATIC_CITY                 1181
#define IDC_STATIC_IP                   1182
#define IDC_SMS_MESSAGE                 1183
#define IDC_UNAME_EDIT                  1183
#define IDC_MESSAGE                     1183
#define IDC_SMS_RESOURCE                1184
#define IDC_UDESC_EDIT                  1184
#define IDC_RESOURCE                    1184
#define IDC_EDIT_DESC                   1185
#define IDC_MAILLIST                    1186
#define IDC_USER                        1187
#define IDC_RESOURCE_NAME               1187
#define IDC_LIST1                       1188
#define IDC_USERNAME                    1189
#define IDC_REQUESTSOURCE               1190
#define IDC_ISSMS                       1191
#define IDC_INFO                        1191
#define IDC_TAB_MOSTNEW                 1192
#define IDC_MailLIST2                   1194
#define IDC_EDIT_URL                    1194
#define IDC_MailLIST3                   1195
#define IDC_fileSTATIC                  1195
#define IDC_MailLIST1                   1196
#define IDC_Agree                       1197
#define IDC_DownLoadFiles               1197
#define IDC_filename                    1198
#define IDC_stat                        1198
#define IDC_ChargeFileList              1199
#define IDC_Sender                      1200
#define IDC_FileList                    1201
#define IDC_Refuser                     1202
#define IDC_Reason                      1203
#define ID_SHOWUI                       32771
#define ID_HIDEUI                       32772
#define ID_MENUITEM32777                32777
#define ID_MENUITEM32778                32778
#define ID_MENUITEM32779                32779
#define ID_MENUITEM_LIST                32780
#define ID_MENUITEM_REPORT              32781
#define ID_MENUITEM_CONFIG              32782
#define ID_MENUITEM_READ                32783
#define ID_MENUITEM_MOVE                32784
#define ID_MENUITEM_COPY                32785
#define ID_MENUITEM_DELETE              32786
#define ID_MENUITEM_OPENFOLDER          32787
#define ID_MENUITEM_ADDFOLDER           32788
#define ID_MENUITEM_DELFOLDER           32789
#define ID_MENUITEM_ORDER               32791
#define ID_MENUITEM_SYN                 32792
#define ID_MENUITEM_DOWNLOAD            32793
#define ID_MENUITEM_TITLE               32794
#define ID_MENUITEM_CREATEDATE          32795
#define ID_MENUITEM_SHAREUSER           32796
#define ID_MENUITEM_FILETYPE            32797
#define ID_MENUITEM_DOWNTIME            32798
#define ID_MENUITEM_ISACTIVE            32799
#define ID_MENUITEM_SIZE                32803
#define ID_MENUITEM_CREATERG            32804
#define ID_MENUITEM_SEARCHRG            32805
#define ID_MENUITEM_REFRESH             32806
#define ID_MENU_CREATE_REGROUP          32807
#define ID_MENU_CREATE_LEVELGROUP       32808
#define ID_MENU_DELETE                  32809
#define ID_MENU_KEYWORDS                32810
#define ID_MENU_TOMYFAVOR               32811
#define ID_MENUITEM_BACKUP              32812
#define ID_MENU_SHOWTAG                 32813
#define ID_MENUITEM_COMMLOG             32814
#define ID_MENUITEM_COMMANAL            32815
#define ID_MENUITEM_RICKRESOURCE        32816
#define ID_MENUITEM_RICKERINFO          32817
#define ID_MENUITEM_TOMYSTUDY           32818
#define ID_MENUITEM_ADDUNIVERSITY       32819
#define ID_MENUITEM_ADDHALL             32820
#define ID_TOOLS_READWOLF               32821
#define ID_TOOLS_MAKEWOLF               32822
#define ID_MENU_STOPDOWNLOAD            32823
#define ID_MENUITEM_MODIFY              32824
#define ID_MENU_ADDNETBOOK              32825
#define ID_MENU_SETNETBOOK              32826
#define ID_MENU_DELNETBOOK              32827
#define ID_MENU_MOVEUP                  32828
#define ID_MENU_MAKEBOOK                32829
#define ID_MENUITEM_REMOVE              32830
#define IDC_MENUITEM_MAKEBOOK           32831
#define IDC_MENUITEM_ADDRICKER          32832
#define IDC_MENUITEM_DELETERICKER       32833
#define ID_MENUITEM_SCORE               32834
#define ID_GFX_SMALLICON                50000
#define ID_GFX_LARGEICON                50001
#define ID_GFX_RENAMEITEM               50002
#define ID_GFX_REMOVEITEM               50003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        367
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1201
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
